[package]
name = "hello_solana"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.0"
borsh-derive = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
solana-program = "=1.17.25"

[lib]
name = "hello_solana"
crate-type = ["cdylib", "lib"]
