[package]
name = "hangman"
version = "0.1.0"
authors = ["Abraham <cedenoabraham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = "1.5.1"
rand = "0.8.3"
